FB-387 Fix change order status on deposit/withdraw
rarible/flow-nft-indexer pull request #228
Opened 2021-11-14 16:42 UTC by zhalninde

2021-11-14 17:51 UTC, atapin requested changes

2021-11-14 17:51 UTC, atapin commented on scanner/src/main/kotlin/com/rarible/flow/scanner/service/OrderService.kt
> +        val status = suspend {
здесь не нужен suspend, потому что `coFindById` саспендится

2021-11-15 04:36 UTC, atapin approved these changes

2021-11-15 05:44 UTC, zolt approved these changes

2021-11-15 09:40 UTC, merged