FB-413 ownerships deduplication
rarible/flow-nft-indexer pull request #243
Opened 2021-11-22 09:35 UTC by atapin

2021-11-22 10:22 UTC, zolt requested changes

2021-11-22 10:22 UTC, zolt commented on scanner/src/main/kotlin/com/rarible/flow/scanner/migrations/ChangeLog00009DeduplicateOwnerships.kt
> +                "}"
в котлине можно в многостроки через 
```
const val migrationCommand = """
   тут всё остальное
  без лишних слешей
"""
```

2021-11-22 10:22 UTC, zolt commented on scanner/src/main/kotlin/com/rarible/flow/scanner/migrations/ChangeLog00009DeduplicateOwnerships.kt
> +        const val OWNERSHIP = "ownership"
private надо бы все эти константы сделать

2021-11-22 10:22 UTC, zolt commented on scanner/src/test/kotlin/com/rarible/flow/scanner/migrations/DeduplicateOwnershipsTest.kt
> +        val logger by Log()
это тоже можно просто private сделать не оборачивая в companion object

2021-11-22 15:07 UTC, zhalninde approved these changes

2021-11-23 08:37 UTC, atapin commented on scanner/src/main/kotlin/com/rarible/flow/scanner/migrations/ChangeLog00009DeduplicateOwnerships.kt
> +                "}"
нельзя доллары эскейпить

2021-11-23 11:54 UTC, zolt approved these changes

2021-11-23 12:00 UTC, merged