FB-256 balance indexer
rarible/flow-nft-indexer pull request #256
Opened 2021-11-30 08:22 UTC by atapin

2021-12-03 04:24 UTC, zhalninde requested changes

2021-12-03 04:24 UTC, zhalninde commented on scanner/src/main/kotlin/com/rarible/flow/scanner/subscriber/fungible/FusdSubscriber.kt
> +                address = "01658d9b94068f3c", //TODO paste correct address
0xe223d8a629e49c68

https://github.com/onflow/fusd

2021-12-03 04:24 UTC, zhalninde commented on scanner/src/main/kotlin/com/rarible/flow/scanner/subscriber/fungible/FusdSubscriber.kt
> +                address = "1654653399040a61",
0x3c5959b568896393

2021-12-03 04:24 UTC, zhalninde commented on scanner/src/main/kotlin/com/rarible/flow/scanner/subscriber/fungible/FungibleTokenSubscriber.kt
> +class FungibleTokenSubscriber(
наверно FlowTokenSubscriber

2021-12-03 04:24 UTC, zhalninde commented on scanner/src/main/kotlin/com/rarible/flow/scanner/subscriber/fungible/FungibleTokenSubscriber.kt
> +                address = "01658d9b94068f3c", //TODO paste correct address
0x7e60df042a9c0868

https://docs.onflow.org/core-contracts/flow-token/

2021-12-03 04:24 UTC, zhalninde commented on scanner/src/main/kotlin/com/rarible/flow/scanner/subscriber/fungible/FungibleTokenSubscriber.kt
> +                address = "f8d6e0586b0a20c7", //TODO paste correct address
0x0ae53cb6e3f42a79

2021-12-03 06:11 UTC, zolt approved these changes

2021-12-13 09:11 UTC, zhalninde requested changes

2021-12-13 09:11 UTC, zhalninde commented on scanner/src/main/kotlin/com/rarible/flow/scanner/subscriber/fungible/FusdSubscriber.kt
> +                address = "3c5959b568896393",
0xe223d8a629e49c68

2021-12-16 09:45 UTC, zolt requested changes

2021-12-16 09:45 UTC, zolt commented on scanner/src/main/kotlin/com/rarible/flow/scanner/subscriber/fungible/FusdSubscriber.kt
> +                startFrom = 1L,
нет такого блока

2021-12-16 09:45 UTC, zolt commented on scanner/src/main/kotlin/com/rarible/flow/scanner/subscriber/fungible/FusdSubscriber.kt
> +                startFrom = 1L,
тут можно совсем убрать startFrom

2021-12-16 10:52 UTC, zhalninde approved these changes

2021-12-16 10:57 UTC, zolt approved these changes

2021-12-16 10:58 UTC, merged