update pipeline release
rarible/flow-nft-indexer pull request #257
Opened 2021-12-02 13:26 UTC by nikolay-ryabinin-rarible

dev,e2e,staging deploy moved to the proxy-staging network

2021-12-03 04:23 UTC, atapin requested changes

2021-12-03 04:23 UTC, atapin commented on cicd/deploy/values.yaml
> +    repository: flow-nft-indexer-backend-api
@nikolay-ryabinin-rarible can we set these values to `flow-backend-api` and `flow-scanner`?

2021-12-03 11:45 UTC, nikolay-ryabinin-rarible commented on cicd/deploy/values.yaml
> +    repository: flow-nft-indexer-backend-api
These values configured automatically with pattern ${env.GIT_REPO_NAME}-${folder_path}

2021-12-07 06:52 UTC, atapin approved these changes

2021-12-07 06:52 UTC, merged