FB-235 CNN support
rarible/flow-nft-indexer pull request #267
Opened 2021-12-13 03:58 UTC by atapin

2021-12-13 04:20 UTC, zolt requested changes

2021-12-13 04:20 UTC, zolt commented on backend-api/src/main/kotlin/com/rarible/flow/api/metaprovider/CnnNFTMetaProvider.kt
> +        val url = "https://onchain.mugenart.io/flow/nft/0x2cd46d41da4ce262/metadata/${itemId.tokenId}"
чую не тот это URL для меты

2021-12-14 07:29 UTC, zolt approved these changes

2021-12-14 07:38 UTC, zhalninde approved these changes

2021-12-14 07:38 UTC, merged