FB-497 update makeStock with balance moves
rarible/flow-nft-indexer pull request #303
Opened 2021-12-22 10:37 UTC by atapin

2021-12-22 10:49 UTC, zolt requested changes

2021-12-22 10:49 UTC, zolt commented on backend-core/src/main/kotlin/com/rarible/flow/core/converter/OrderToDtoConverter.kt
> +                makeStock = source.makeStock.movePointRight(multiplier).toBigInteger(), //TODO make BigDecimal
уже сделано

2021-12-22 10:49 UTC, zolt commented on backend-core/src/main/kotlin/com/rarible/flow/core/domain/item.kt
> +    val listed: Boolean = false, //TODO remove, not used
тут что ты имеешь ввиду? мы этот флажок переключаем, когда ордера создаются/закрываются

2021-12-22 10:49 UTC, zolt commented on scanner/src/main/kotlin/com/rarible/flow/scanner/eventlisteners/OrderIndexerEventProcessor.kt
> -                }
в `sendUpdate` нет вот этой части, чонить налюбнётся пади

2021-12-22 10:49 UTC, zolt commented on scanner/src/main/kotlin/com/rarible/flow/scanner/service/BidService.kt
> +    }
логгер не обязательно выносить в `companion object` достаточно объявить его как `private val`

2021-12-22 11:23 UTC, atapin commented on scanner/src/main/kotlin/com/rarible/flow/scanner/eventlisteners/OrderIndexerEventProcessor.kt
> -                }
... поэтому айтемы не надо обновлять при движении ордеров

2021-12-22 11:31 UTC, atapin commented on backend-core/src/main/kotlin/com/rarible/flow/core/converter/OrderToDtoConverter.kt
> +                makeStock = source.makeStock.movePointRight(multiplier).toBigInteger(), //TODO make BigDecimal
это же во flow-protocol-api должно быть изменено. добавил PR https://github.com/rarible/flow-protocol-api/pull/57/

2021-12-22 12:09 UTC, zolt commented on backend-core/src/main/kotlin/com/rarible/flow/core/converter/OrderToDtoConverter.kt
> +                makeStock = source.makeStock.movePointRight(multiplier).toBigInteger(), //TODO make BigDecimal
это поправлено прям тут в конвертере

2021-12-22 12:21 UTC, atapin commented on backend-core/src/main/kotlin/com/rarible/flow/core/converter/OrderToDtoConverter.kt
> +                makeStock = source.makeStock.movePointRight(multiplier).toBigInteger(), //TODO make BigDecimal
fixed

2021-12-22 12:21 UTC, atapin commented on scanner/src/main/kotlin/com/rarible/flow/scanner/service/BidService.kt
> +    }
fixed

2021-12-22 12:26 UTC, zhalninde approved these changes

2021-12-23 04:28 UTC, zolt approved these changes

2021-12-23 04:30 UTC, merged