FB-455 Add Versus art NFT
rarible/flow-nft-indexer pull request #333
Opened 2022-01-13 12:48 UTC by zhalninde

2022-01-13 16:06 UTC, atapin commented on backend-api/src/main/kotlin/com/rarible/flow/api/metaprovider/VersusArtMetaProvider.kt
> +            ItemMetaAttribute("schema", nft.schema.toString()),
what kind of data is stored here? the attributes model UI filter. would this data fit to be a filter value?

2022-01-13 16:07 UTC, atapin requested changes
need tests at least for happy paths

2022-01-13 17:13 UTC, zhalninde commented on backend-api/src/main/kotlin/com/rarible/flow/api/metaprovider/VersusArtMetaProvider.kt
> +            ItemMetaAttribute("schema", nft.schema.toString()),
the attributes stored in the NFT are stored here. don't know anything about filtering

2022-01-18 07:10 UTC, zolt approved these changes

2022-01-20 10:06 UTC, atapin approved these changes

2022-01-20 10:09 UTC, merged