FB-513 starly
rarible/flow-nft-indexer pull request #369
Opened 2022-01-31 05:29 UTC by atapin

2022-01-31 05:39 UTC, zolt requested changes

2022-01-31 05:39 UTC, zolt commented on scanner/src/main/kotlin/com/rarible/flow/scanner/subscriber/StarlyCardSubscriber.kt
> +            )
а на тестнете их нет? надо добавить

2022-02-01 10:28 UTC, zhalninde approved these changes

2022-02-02 05:18 UTC, zolt approved these changes

2022-02-02 05:19 UTC, merged