FB-566 Fanfare support
rarible/flow-nft-indexer pull request #400
Opened 2022-02-14 10:10 UTC by atapin

2022-02-14 10:11 UTC, zhalninde approved these changes

2022-02-14 10:21 UTC, zolt requested changes

2022-02-14 10:21 UTC, zolt commented on backend-api/src/main/kotlin/com/rarible/flow/api/metaprovider/FanfareProvider.kt
> +
1) `private`
2) ObjectMapper лучше создавать через функцию `jacksonObjectMapper()`

2022-02-14 10:21 UTC, zolt commented on backend-api/src/main/kotlin/com/rarible/flow/api/service/UserStorageService.kt
> +        val objectMapper = ObjectMapper().registerKotlinModule()
`jacksonObjectMapper()`

2022-02-14 10:21 UTC, zolt commented on scanner/src/main/kotlin/com/rarible/flow/scanner/subscriber/FanfareSubscriber.kt
> +                startFrom = 22741361,
не надо ставить `startFrom` для TESTNET, ибо мы знаем только про текущий спорк, тут будет падать на `dev` и `stage` окружении т.к. не сможет получить блок

2022-02-15 04:33 UTC, zolt approved these changes

2022-02-15 04:34 UTC, merged