FB-659 Add purchase field to FlowTransferDto
rarible/flow-nft-indexer pull request #445
Opened 2022-04-07 11:35 UTC by zhalninde

2022-04-07 11:41 UTC, zolt requested changes

2022-04-07 11:41 UTC, zolt commented on scanner/src/main/kotlin/com/rarible/flow/scanner/eventlisteners/ItemIndexerEventProcessor.kt
> +            if (event.source != Source.REINDEX) {
сейчас вроде всегда шлём в кафку

2022-04-07 11:41 UTC, zolt commented on backend-core/src/main/kotlin/com/rarible/flow/core/repository/ItemHistoryRepository.kt
> +                { "activity.left.maker": ?2, "activity.right.maker": ?1 }
ещё бы индекс накрутить на эти поля, если нет такого

2022-04-07 18:41 UTC, zhalninde commented on backend-core/src/main/kotlin/com/rarible/flow/core/repository/ItemHistoryRepository.kt
> +                { "activity.left.maker": ?2, "activity.right.maker": ?1 }
добавил

2022-04-07 18:42 UTC, zhalninde commented on scanner/src/main/kotlin/com/rarible/flow/scanner/eventlisteners/ItemIndexerEventProcessor.kt
> +            if (event.source != Source.REINDEX) {
+
ой не везде

2022-04-08 04:25 UTC, zolt approved these changes

2022-04-08 04:32 UTC, atapin approved these changes

2022-04-08 05:35 UTC, merged