FB-698 Add dbUpdatedAt to Flow for Orders
rarible/flow-nft-indexer pull request #458
Opened 2022-04-15 12:04 UTC by zhalninde

2022-04-15 12:07 UTC, zolt approved these changes

2022-04-15 12:14 UTC, atapin requested changes

2022-04-15 12:14 UTC, atapin commented on backend-core/src/main/kotlin/com/rarible/flow/core/domain/order.kt
> +    val dbUpdatedAt: LocalDateTime = LocalDateTime.now()
let's use Instant

2022-04-15 12:14 UTC, atapin commented on backend-core/src/main/kotlin/com/rarible/flow/core/repository/OrderRepository.kt
> +            .apply(update.set(Order::dbUpdatedAt.name, LocalDateTime.now()))
this change should go to a migration

2022-04-18 02:56 UTC, zolt approved these changes

2022-04-18 06:48 UTC, zhalninde commented on backend-core/src/main/kotlin/com/rarible/flow/core/domain/order.kt
> +    val dbUpdatedAt: LocalDateTime = LocalDateTime.now()
ок

2022-04-18 06:48 UTC, zhalninde commented on backend-core/src/main/kotlin/com/rarible/flow/core/repository/OrderRepository.kt
> +            .apply(update.set(Order::dbUpdatedAt.name, LocalDateTime.now()))
done

2022-05-18 09:14 UTC, atapin approved these changes

2022-05-18 09:14 UTC, merged